server:
  port: 9101
  max-http-header-size: 2MB
  servlet:
    context-path: /sms
spring:
  application:
    name: waveedu-sms
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    hiddenmethod:
      filter:
        enabled: true #启用HiddenHttpMethodFilter,支持rest风格
  redis:
    host: 8.134.136.211
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
sms:
  # 应用的AppID
  appId: 1400791280
  # 应用的App Key
  appKey: cbd511ed24bd832d05af54f63c84e52d
  # 签名的内容
  signContent: 狐狸半面添公众号
  # 登录&注册短信模板的id
  loginTemplateId: 1671035









