spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/wave_edu?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #指定数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  application:
    name: waveedu-basic
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  redis:
#    database: 0
#    host: 1.15.72.167
#    port: 6379
#    password: F1125@ye*
#    lettuce.pool.max-active: 8
#    lettuce.pool.max-wait: -1
#    lettuce.pool.max-idle: 8
#    lettuce.pool.min-idle: 0
  mvc:
    hiddenmethod:
      filter:
        enabled: true #启用HiddenHttpMethodFilter,支持rest风格
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

server:
  port: 9001
  max-http-header-size: 2MB

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: assign_id #使用雪花算法生成id
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    #这里我们配置出底层的sql，可以输出sql日志信息，方便我们观察
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









